### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by mariasmo** [CVxTz/xumi#2]
Hi,

The train.py file has some has some default files of reddit_full_text.txt and amazon_full_text.txt. What are these files?

Also, would you be able to upload the 2 million sentences you used to train the data (both the original sentence and the perturbed sentence)? If not how can i generate such data? 

Thanks

**Comment by CVxTz** [comment]
Hello

Those files are used to build the tokenizer. You can just use the one versioned with the code and not retrain your own.

To train the spell checker itself, you will only need wikisent2, can be found here -> https://www.kaggle.com/datasets/mikeortman/wikipedia-sentences 

Best,
